### ISSUE TITLE
Gas & Fee

### ISSUE THREAD

**Issue by grarco** [anoma/namada#1010]
Depends on #976 for wrapper txs to be included first in a block and max_gas block compliance

# TODO

- [x] #889 
- [ ] Add gas accounting mechanism (#1242)
    - `mempool_validate` check on the `GasLimit`
    - `process_proposal` check on the `GasLimit`
    -  `prepare_proposal` check on the `GasLimit`
    - In storage table of gas for every whitelisted tx/vp
    - `finalize_block` computation of the actual gas used and validation of the tx/block
    - Update client to produce wrappers with the correct `GasLimit` (account also for compilation costs)
    - Testing
    - Linear accounting of signatures verification (multisig #1102) -> Get the amount of signatures from `SignedTxData` and define a multiplicative coefficient given the cost of a single signature verification
    - No need to set gas as `i64` for tendermint compatibility anymore since we don't care about passing the used gas to tendermint (see [this](https://github.com/tendermint/abci/issues/57) issue and [this](https://github.com/tendermint/tendermint/issues/1065) one)
- [ ] Add optional unshielding in `WrapperTx` (#1281)
    - `mempool_validate`check
    - `process_proposal` check
    - `prepare_proposal` check
    - `finalize_block` unshield execution
    - update client
    - e2e tests
- [ ] Adjust the balance checks added in #962 to be coherent with the proposed specification
    - `mempool_validate` check
    - Correct `FeeAmount` in client, no default in cli and set default to the storage parameter
    - Define the cost for unit of gas in storage (parameter) + whitelisted assets + checks
    - `process_proposal` check
    - Fee payment in `finalize_block`
    - Force order of txs (wrappers first) in `process_proposal` (should already be done in #976)
    - Remove fixed fee from protocol parameters
    - Unit testing (transfer to block proposer, fee with invalid token)
    - Devnet testing (especially more unshielding in a single block)
    - Adjust `dry_run_tx` to handle a `WrapperTx` for a correct gas estimation
    - Define genesis values
