### ISSUE TITLE
Implement the Ethereum bridge validity predicate

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#114]
This is a top-level issue for tracking development of the EthBridge VP

- [x] Internal address for the #EthBridge ([anoma#1066](https://github.com/anoma/anoma/pull/1066))
- [x] Guard the #EthBridge against disallowed modifications
- [x] Implement the multitoken interface to represent wrapped ERC20s
- [x] Transfers of wrapped ERC20s between users should be permitted. (https://github.com/anoma/namada/issues/427)
- [x] Only authorized ERC20 transfers should be permitted (https://github.com/anoma/namada/issues/432)

Related: transfer logic for multitokens more generally will be covered by anoma/namada#132

**Comment by cwgoes** [comment]
@james-chf what is the status of this? still blocked on #432 ?

**Comment by james-chf** [comment]
I'll check if https://github.com/anoma/namada/issues/432 is finished and has test coverage, once that's done this issue can be closed
