### ISSUE TITLE
[tracking] Key generation

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2002]
dependencies:
- [ ] https://github.com/anoma/namada/issues/7
- [ ] https://github.com/anoma/namada/issues/70
- [ ] https://github.com/anoma/namada/pull/1782
- [ ] https://github.com/anoma/namada/pull/1840
- [ ] Some interface work presumably, but I didn't find any issue for it /cc @jurevans @mateuszjasiuk 
- [ ] Ledger updates by @murisi (ditto, please link/make an issue)

---

This issue tracks feature-completness of key generation. Key generation is feature-complete if and only if:
- users can generate keys using the Namada CLI (which should use the same code as the SDK uses - DRY)
  - manually (random mnemonic)
  - using the Ledger hardware wallet 
- users can generate keys using the Namada interface
  - manually (random mnemonic)
  - using the Ledger hardware wallet 
- users can use these keys to generate appropriate signatures as required for genesis transactions and afterwards
- we're confident that key generation is secure and final (no further changes)

Please add any dependencies that you believe are necessary to meet these requirements in the list above.

related: https://github.com/anoma/namada/issues/1950
