### ISSUE TITLE
[tracking] Transparent airdrop readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2003]
dependencies:
- [x] https://github.com/anoma/namada/issues/1394
- [x] https://github.com/anoma/namada-interface/issues/424
- [x] https://github.com/anoma/namada/issues/2002
- [x] https://github.com/anoma/namada/issues/2038

---

This issue tracks feature-completeness of the transparent airdrops to Osmosis & the Cosmos Hub.

Transparent airdrops are feature complete if and only if:
- Users can sign a message using their Osmosis/Cosmos-compatible keys, which we can validate in a special claiming VP (see the first dependency)
- When validated by the special claiming VP, this message allows the user to claim some preconfigured token amount from that VP
  - TODO @awasunyin decide if other conditions need to be met
  - TODO @awasunyin decide if we want to do a pre-genesis airdrop claim process instead
- A user who provides a valid signature can execute this transaction without any fees (since they probably don't have NAM)
- The interface implements a page and code to support claiming these airdrops using Keplr
- All airdrop-related code is tested, believed to be complete, and audited by at least two people other than the author

Please add any dependencies that you believe are necessary to meet these requirements in the list above.

**Comment by nguyenbaongocbkhn** [comment]
no see

**Comment by cwgoes** [comment]
ref https://github.com/anoma/namada/issues/2038

**Comment by cwgoes** [comment]
ref https://github.com/anoma/namada/issues/2041
