### ISSUE TITLE
[tracking] Genesis generation readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2004]
dependencies:
- [x] https://github.com/anoma/namada/issues/2002
- [x] https://github.com/anoma/namada/issues/1155
- [x] https://github.com/anoma/namada/issues/1048
- [x] https://github.com/anoma/namada/issues/1034
- [x] https://github.com/anoma/namada/issues/1033
- [x] https://github.com/anoma/namada/issues/711
- [x] https://github.com/anoma/namada/issues/106 (already done in genesis)
- [x] https://github.com/anoma/namada/issues/45
- [x] #1881 
- [x] #2008 
- [x] https://github.com/anoma/namada/issues/2018
- [ ] https://github.com/anoma/namada/issues/2026
- [x] https://github.com/anoma/namada/issues/1265
- [x] https://github.com/anoma/namada/issues/761
- [x] https://github.com/anoma/namada/issues/112
---

This issue tracks feature-completeness of genesis generation. Genesis generation is feature-complete if and only if:
- Users can generate a pre-genesis configuration with initial parameters
- Other users can generate genesis transactions, including:
    - Registering to a validator
    - Bonding to a validator
-  All genesis-related code is tested, believed to be complete, and internally audited by at least two people other than the author

Please add any dependencies that you believe are necessary to meet these requirements in the list above.
