### ISSUE TITLE
[tracking] Governance & PGF readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2005]
dependencies:
- [x] https://github.com/anoma/namada/issues/1107
- [x] https://github.com/anoma/namada/pull/1979
- [x] #2053 
- [x] https://github.com/anoma/namada/issues/2090
---

Edit from @adrianbrink 

Generally we don't need any of the PGF features for milestone 1. We only need the ability for someone to submit a proposal and have validators/delegators vote on that proposal.

---

This issue tracks feature-completeness of governance. Governance is feature-complete if and only if:
- Everything in the [governance specs](https://specs.namada.net/governance) and [public goods funding specs](https://specs.namada.net/economics/public-goods-funding) is implemented.
- All governance and PGF-related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.

**Comment by grarco** [comment]
I've also added the need to run rPGF payments at genesis

**Comment by adrianbrink** [comment]
> I've also added the need to run rPGF payments at genesis

We don't need this for milestone 1.

**Comment by adrianbrink** [comment]
Generally we don't need any of the PGF features for milestone 1. We only need the ability for someone to submit a proposal and have validators/delegators vote on that proposal.
