### ISSUE TITLE
[tracking] Proof-of-stake readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2006]
dependencies:

Critical for feature-completeness (must be implemented):
- [x] https://github.com/anoma/namada/issues/17
- [x] https://github.com/anoma/namada/issues/1360
- [x] https://github.com/anoma/namada/issues/36
- [x] https://github.com/anoma/namada/issues/106
- [x] https://github.com/anoma/namada/issues/1270
- [ ] #2055 (replaced ~~https://github.com/anoma/namada/issues/2044~~)
- [x] https://github.com/anoma/namada/issues/21
- [x] https://github.com/anoma/namada/issues/2102
- [x] https://github.com/anoma/namada/issues/34
- [x] https://github.com/anoma/namada/issues/35
- [x] https://github.com/anoma/namada/issues/1130
- [x] https://github.com/anoma/namada/issues/1556
- [x] https://github.com/anoma/namada/issues/1770
- [x] https://github.com/anoma/namada/issues/1783
- [x] https://github.com/anoma/namada/issues/1798
- [x] https://github.com/anoma/namada/issues/1829
- [x] https://github.com/anoma/namada/issues/1830
- [x] https://github.com/anoma/namada/issues/1857
- [x] https://github.com/anoma/namada/issues/1959
- [x] https://github.com/anoma/namada/issues/1961
- [x] https://github.com/anoma/namada/issues/1981
- [x] https://github.com/anoma/namada/issues/1609
- [x] https://github.com/anoma/namada/issues/2058

Not necessary for feature-completeness but nice to have (implement if we have free time):
- [ ] https://github.com/anoma/namada/issues/769
- [ ] https://github.com/anoma/namada/issues/1508
- [ ] https://github.com/anoma/namada/issues/1125
- [ ] https://github.com/anoma/namada/issues/1832
- [ ] https://github.com/anoma/namada/issues/805
- [x] https://github.com/anoma/namada/issues/1227
- [ ] https://github.com/anoma/namada/issues/1465
- [ ] https://github.com/anoma/namada/issues/1640
- [ ] https://github.com/anoma/namada/issues/1732
- [ ] https://github.com/anoma/namada/issues/1967
- [ ] https://github.com/anoma/namada/issues/2037
- [x] https://github.com/anoma/namada/issues/2057
- [ ] https://github.com/anoma/namada/issues/2059

Possibly not in scope for Namada anymore (don't implement yet):
- [ ] https://github.com/anoma/namada/issues/1126
- [ ] https://github.com/anoma/namada/issues/1127
- [ ] https://github.com/anoma/namada/issues/12
- [ ] https://github.com/anoma/namada/issues/939

Else
- [ ] Probably more, cc @tzemanovic @brentstone 

---

This issue tracks feature-completeness of proof-of-stake. Proof-of-stake is feature-complete if and only if:
- Everything in the [proof-of-stake specs](https://specs.namada.net/economics/proof-of-stake), including incentives, is implemented.
- All proof-of-stake-related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.
