### ISSUE TITLE
[tracking] Network milestone 1 [PoS+Gov+Essentials] readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2007]
dependencies:
- [x] https://github.com/anoma/namada/issues/2002
- [ ] https://github.com/anoma/namada/issues/2004
- [x] https://github.com/anoma/namada/issues/2005
- [x] https://github.com/anoma/namada/issues/2006
- [x] https://github.com/anoma/namada/issues/2019
- [x] https://github.com/anoma/namada/issues/2052
- [x] https://github.com/anoma/namada/issues/1044 for ledger stability
- [x] https://github.com/anoma/namada/issues/2043
- [ ] https://github.com/anoma/namada/issues/2055
- [x] https://github.com/anoma/namada/issues/408 - change VPs to be more cautious on unknown keys changes

---

This issue tracks milestone completeness of network milestone 1. Network milestone 1 is complete if and only if:
- Users can generate keys, craft a genesis file, and perform a decentralized network start.
- Users can use proof-of-stake fully.
- Users can use governance fully, including proposing future upgrades (which may update code or enable other features).
- All related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.

**Comment by adrianbrink** [comment]
My slight alteration:
- PoS only needs to support staking - it doesn't necessarily need to include rewards
- Governance only next to support proposals and not anything related to cPGF

Other than that the list looks good.

**Comment by cwgoes** [comment]
Note: as the feature is already nearly complete, milestone 1 will include proof-of-stake rewards.
