### ISSUE TITLE
[tracking] Gas, fee, and replay protection readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2019]
dependencies:
- [x] https://github.com/anoma/namada/issues/1923
- [x] https://github.com/anoma/namada/issues/1530
- [x] https://github.com/anoma/namada/issues/1924
- [x] #2036
- [x] https://github.com/anoma/namada/pull/1977
- [x] https://github.com/anoma/namada/pull/1905
- [x] https://github.com/anoma/namada/pull/1867
- [x] https://github.com/anoma/namada/pull/1954
- [x] #2054 
- [x] #2056 

---

This issue tracks feature-completeness of the gas, fee, and replay protection systems, along with any associated transaction processing code. Gas, fee, and replay protection are feature-complete if and only if:
- Gas costs are computed in a reasonable and sufficiently DoS-proof manner
- Fees are charged and distributed in the appropriate way
- Replay protection prevents transaction replay, and storage usage is acceptable
- All related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.
