### ISSUE TITLE
[tracking] MASP integration readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2020]
dependencies:
- [ ] https://github.com/anoma/namada/issues/56
- [ ] https://github.com/anoma/namada/issues/302
- [ ] https://github.com/anoma/namada/issues/303
- [ ] https://github.com/anoma/namada/issues/305
- [ ] https://github.com/anoma/namada/issues/307
- [ ] https://github.com/anoma/namada/issues/480
- [ ] https://github.com/anoma/namada/issues/483
- [ ] https://github.com/anoma/namada/issues/862
- [ ] https://github.com/anoma/namada/issues/1373
- [ ] https://github.com/anoma/namada/issues/1374
- [ ] https://github.com/anoma/namada/issues/1376
- [ ] https://github.com/anoma/namada/issues/1730
- [ ] https://github.com/anoma/namada/issues/1376
- [ ] https://github.com/anoma/namada/issues/1677
- [ ] https://github.com/anoma/namada/issues/1962
- [ ] Wallet updates (doesn't check the latest epoch scanned) /cc @Fraccaman is there an issue for this?
- [ ] MASP epoch boundary issue /cc @Fraccaman is there an issue for this? do we know the underlying problem?
- [ ] MASP VP needs to be converted to native code /cc @Fraccaman is there an issue for this?

---

This issue tracks feature-completeness of the MASP integration, including shielded set rewards. The MASP integration is feature-complete if and only if:
- Users can send transparent-to-shielded, shielded-to-shielded, and shielded-to-transparent transactions with any token on Namada
- The ledger correctly computes rewards as per the [specs](https://specs.namada.net/economics/shielded-pool-incentives)
- Users can claim rewards
- The client and SDK handle all MASP-related transactions correctly and consistently, including claiming rewards
- All related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.
