### ISSUE TITLE
[tracking] IBC integration readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2021]
dependencies:
- [x] #2314
- [ ] #2232
- [x] #2153 blocked by ibc-rs v0.48
- [x] #2084
- [x] #2087
- [x] https://github.com/anoma/namada/issues/2015
- [x] https://github.com/anoma/namada/issues/1947
  - [x] #2062
- [x] https://github.com/anoma/namada/issues/1946
- [x] https://github.com/anoma/namada/issues/1923
- [ ] #1831
  - Workaround by #1904
- [ ] https://github.com/anoma/namada/issues/1804
  - Blocked by
    - [x] #2084
    - [ ] Gaia v15? with ibc-go v7 or later (for ics23)
- [x] https://github.com/anoma/namada/issues/1451
- [x] https://github.com/anoma/namada/issues/1445
- [x] https://github.com/anoma/namada/issues/1395
- [x] https://github.com/anoma/namada/issues/485
- [x] https://github.com/anoma/namada/issues/773
  - [x] #1797
- [x] https://github.com/anoma/namada/pull/1989
- [x] https://github.com/anoma/namada/pull/1951
- [x] https://github.com/anoma/namada/pull/1917

---

This issue tracks feature completeness of the IBC integration with Namada. The IBC integration is feature-complete if and only if:
- IBC fully works, including relaying and everything necessary for simple shielded actions (mostly memo fields)
- All related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.
