### ISSUE TITLE
[tracking] Network milestone 2 [MASP+IBC] readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2022]
dependencies:
- [x] https://github.com/anoma/namada/issues/2007
- [ ] https://github.com/anoma/namada/issues/2020
- [ ] https://github.com/anoma/namada/issues/2021

---

This issue tracks milestone completeness of network milestone 2, at which point users can use the MASP with tokens transferred from other chains using IBC (but not yet the Ethereum bridge).

Network milestone 2 is complete if and only if:
- Everything in network milestone 1 is complete.
- The MASP fully works, including shielded set rewards.
- IBC fully works.
- All related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.
