### ISSUE TITLE
[tracking] Ethereum bridge readiness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2023]
dependencies:
- [x] https://github.com/anoma/namada/issues/2110
- [x] https://github.com/anoma/namada/issues/2027
- [ ] https://github.com/anoma/namada/issues/2042
- [ ] https://github.com/anoma/namada/issues/2032
- [ ] https://github.com/anoma/namada/issues/2031
- [ ] https://github.com/anoma/namada/issues/2030
- [ ] https://github.com/anoma/namada/issues/2029
- [ ] https://github.com/anoma/namada/issues/1967
- [ ] https://github.com/anoma/namada/issues/1287
- [x] https://github.com/anoma/namada/issues/1857
- [x] https://github.com/anoma/namada/issues/1800
- [ ] https://github.com/anoma/namada/issues/1787
- [ ] https://github.com/anoma/namada/issues/1726
- [ ] https://github.com/anoma/namada/issues/1720
- [ ] https://github.com/anoma/namada/issues/1703
- [ ] https://github.com/anoma/namada/issues/1160
- [ ] https://github.com/anoma/namada/issues/635
- [ ] https://github.com/anoma/namada/issues/537
- [ ] https://github.com/anoma/namada/issues/508
- [ ] https://github.com/anoma/namada/issues/506
- [ ] https://github.com/anoma/namada/issues/249
- [x] https://github.com/anoma/namada/pull/2012
- [ ] https://github.com/anoma/namada/pull/1995
- [x] https://github.com/anoma/namada/pull/1964
- [x] https://github.com/anoma/namada/pull/1958
- [x] https://github.com/anoma/namada/pull/1957
- [x] https://github.com/anoma/namada/pull/1956
- [x] https://github.com/anoma/namada/pull/1944
- [ ] https://github.com/anoma/namada/pull/1780

---

This issue tracks feature completeness of the Ethereum bridge integration with Namada. The Ethereum bridge integration is feature-complete if and only if:
- The Ethereum bridge fully works, including relaying.
- All related code is tested, believed to be complete, and internally audited by at least two people other than the author.

Please add any dependencies that you believe are necessary to meet these requirements in the list above.

**Comment by cwgoes** [comment]
Switched to planning via project boards.
