### ISSUE TITLE
Internal review checklist for proof-of-stake

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2072]
- [x] Everything critical in https://github.com/anoma/namada/issues/2006 is complete
- [x] Reviewed by @cwgoes from the specs/design angle
- [x] Reviewed by @Fraccaman @bengtlofgren from the testing angle
- [x] Run on the public testnet for at least a few days
