### ISSUE TITLE
Internal review checklist for gas, fees, and replay protection

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2074]
- [x] Everything critical in https://github.com/anoma/namada/issues/2019 is complete
- [ ] Reviewed by @cwgoes from the specs/design angle
- [ ] Reviewed by @Fraccaman @bengtlofgren from the testing angle
- [x] Run on the public testnet for at least a few days
