### ISSUE TITLE
Internal review checklist for genesis flow

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2075]
- [ ] Everything critical in https://github.com/anoma/namada/issues/2004 is complete
- [ ] Reviewed by @cwgoes from the specs/design angle
- [ ] Reviewed by @Fraccaman @bengtlofgren from the testing angle
- [ ] Run on the public testnet for at least a few days
