### ISSUE TITLE
Milestone 1 ready for incentivized testnet

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2076]
Dependencies:
- [x] https://github.com/anoma/namada/issues/2007
- [x] https://github.com/anoma/namada/issues/2072
- [x] https://github.com/anoma/namada/issues/2073
- [x] https://github.com/anoma/namada/issues/2074
- [x] https://github.com/anoma/namada/issues/2075

This issue tracks when the milestone 1 software release will be ready for the incentivized testnet.

**Comment by adrianbrink** [comment]
It should also include https://github.com/anoma/namada/issues/2093
