### ISSUE TITLE
Mainnet phases of operation

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2563]
*This list is still tentative and subject to change.*

The following must happen _before mainnet_:

1. [ ] Attain protocol stability.
    - Protocol stability requires that the community (including Heliax) is confident in the correctness of and familiar with the usage of a stable version of the software. 
    - At minimum, this requires a release version which we intend to use for mainnet. This release version must:
        - [ ] Complete everything in https://github.com/anoma/namada/issues/2528, software-wise.
        - [ ] Be run on the SE for 1-2 weeks stably
        - [ ] Be subjected to 2 weeks of full-time internal red teaming with no further finds
        - [ ] Be subjected to final external audits (details still TBD)
2. [ ] Finalize a genesis block proposal and publish it alongside instructions to:
    - Reconstruct the generation process using input data.
    - Check for the presence of an account in the genesis file, and the associated balance.
    - Check that the keys associated with this account are accessible and can produce a valid signature.
3. [ ] Genesis block proposal is published for at least 1 week of community review
    - People should have a chance to test their keys. This is the last time we can change addresses.

Mainnet is expected to follow the following _phases_ (names are tentative):

**Phase 1: Block Party**

- No staking, PGF, or shielded set rewards inflation.
- Only proof-of-stake and governance features are enabled.
- IBC rate limits for all assets are set to 0. Clients, connections, and channels can be created, but no assets can be transferred in.
- NAM transfers are disabled.
- During this phase, if anything goes horribly wrong, it is probably possible to reset the network.

**Phase 2: Staking Party**

- Staking inflation and PGF inflation are turned on via a governance proposal.

**Phase 3: Shielding Party**

- IBC rate limits for selected assets are slowly raised in a sequence of governance proposals.
    - e.g. ATOM, OSMO, USDC
- These assets may be transferred transparently and using the MASP.
- NAM transfers are still disabled.

**Phase 4: Shielding Party Overdrive**

- Shielded set rewards are slowly turned on for selected assets in a sequence of governance proposals.
- NAM transfers are still disabled.
- At this point, all features of the protocol are operational, and we can slowly increase limits as stability is demonstrated.

**Phase 5: NAM NAM NAM**

- Eventually, if the network is stable and the community feels ready, NAM transfers can be enabled.
- This is the last phase in the initial launch sequence.

**Comment by brentstone** [comment]
What does it look like to disable NAM transfers in the code? It sounds like before we want to enable them, accounts will still be able to bond and unbond tokens and make governance proposals. These actions require transferring tokens to and from an account and an internal address like PoS or Governance. Perhaps we have some logic that forbids transfers between (implicit | established) <---> (implicit | established) addresses?

**Comment by cwgoes** [comment]
> What does it look like to disable NAM transfers in the code? It sounds like before we want to enable them, accounts will still be able to bond and unbond tokens and make governance proposals. These actions require transferring tokens to and from an account and an internal address like PoS or Governance. Perhaps we have some logic that forbids transfers between (implicit | established) <---> (implicit | established) addresses?

Yes; I think we would only allow transfers to and from PoS and governance, and the transfers back can only be to the account which controlled the bond or made the deposit, respectively.

**Comment by samwang3** [comment]
> > What does it look like to disable NAM transfers in the code? It sounds like before we want to enable them, accounts will still be able to bond and unbond tokens and make governance proposals. These actions require transferring tokens to and from an account and an internal address like PoS or Governance. Perhaps we have some logic that forbids transfers between (implicit | established) <---> (implicit | established) addresses?在代码中禁用 NAM 传输是什么样子的？听起来好像在我们想要启用它们之前，帐户仍然能够绑定和解除绑定代币并提出治理建议。这些操作需要在账户和内部地址（如 PoS 或治理）之间传输代币。也许我们有一些逻辑禁止（隐式|已建立）<--->（隐式|已建立）地址之间的传输？
> 
> Yes; I think we would only allow transfers to and from PoS and governance, and the transfers back can only be to the account which controlled the bond or made the deposit, respectively.是的;我认为我们只允许在 PoS 和治理之间进行转账，并且转回只能分别转至控制债券或存款的账户。

hey sir
I'm sorry to disturb you, our unjail-validator is in jail, please tell me when it can be unlocked, because many tasks cannot be submitted in jail, btw, we are making a good-looking explorer, thx

**Comment by brentstone** [comment]
@samwang3 this is not the appropriate location or issue for this kind of question.

First, we encourage you to ask such questions on Discord - github issues should be used for reporting actual software issues.

Second, there are several issues on github addressing this already - #2663, #2642, #2640. In short, the issue is addressed in #2617, which will come at the next release that is made with breaking changes.

**Comment by ahaunz** [comment]
As I understand it, the concept is that when Phase 5 is reached, the entire 100% of the 1b (NAM) supply will become available for transfer/transfers. And no vesting for all of them.

How useful is this in terms of tokenomics and long term development of Namada, how does launching the first fractal instance of Anoma follow such a method?

Because of this approach, the support of the long-term and retail investor is lost, including there may be a problem with listing on the CEX exchanges and with this approach developers will have no incentive to continue to support and develop the project, because with this approach its value/value of NAM including will tend to zero.

Still, I suggest to consider creating a more fair and accurate tokenomics, for example, to pay attention to Celestia (With a small amount of unlocked assets for the community/developers/treasury, about 12-18% at the time of listing followed by gradual unlocking of the rest)

**Comment by ragnarok5562** [comment]
Let me ask a simple question. The testnet has been running for so long and the above problems were solved before the mainnet was launched. Why can’t the mainnet transfer tokens yet but continue to do testing? Are you sure this is the mainnet and not testnet 2?

**Comment by cryptomolot** [comment]
The proposed plan appears promising, with the flexibility to make adjustments through governance. The Namada community and pilots, in particular, will play a crucial role in ensuring its success :)

Viva La Namada!

**Comment by Zipporol** [comment]
Do I understand correctly that after the launch of the mainnet we will have to go through the same stages as in the shielded expedition? How long might it take to complete all stages?

**Comment by brlck974** [comment]
great team , i like this plan

**Comment by ValarDragon** [comment]
X-posting my comment from the forums:

Exciting that this is happening!

Phase 1 makes sense to me to start getting some user-determined validator set choices determined. I personally would hope that this phase is like 3 days, but at most 2 weeks.

I don’t get why phase 2 and phase 3 can’t be combined. I don’t really see any point in turning on staking inflation prior to allowing IBC. I think it will lead to phase 2 user frustration to have to stake early for yield, but come back later to do their first thing here. (The NAM they get won’t even be distributable) Hence I think just combine phase 2 + 3 and jump to utility being provided. Seems like an unnecessary delay in time to market, with unclear utility to me.

**Comment by gavinly** [comment]
fyi this is also being discussed on the Namada forum: https://forum.namada.net/t/proposal-for-mainnet-launch-phases/560

**Comment by cwgoes** [comment]
Out-of-date, superseded by more recent discussions on the forums.
