### ISSUE TITLE
Mainnet product requirements checklist 2023.01.05

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#982]
- Consensus
  - [ ] Tendermint 0.37 release _blocked on upstream_  
  - [ ] tmkms compatibility testing (also for Ethereum bridge keys) https://github.com/anoma/namada/issues/67
    - [x] Basic Tendermint integration
    - [ ] Additional keys
- Proof-of-stake
  - [ ] Delegation, undelegation, redelegation - https://github.com/anoma/namada/pull/740
  - [ ] NAM reward distribution - https://github.com/anoma/namada/pull/714
  - [ ] Liveness slashing - https://github.com/anoma/namada/pull/981
  - [ ] Safety slashing - https://github.com/anoma/namada/pull/892 
  - [ ] Validator multisignature keys (for control/voting) - https://github.com/anoma/namada/pull/680 (specs)
- Gas & fees
  - [ ] Gas metering - https://github.com/anoma/namada/pull/889 (specs)
  - [ ] Transaction fee implementation - https://github.com/anoma/namada/pull/889 (specs)
- Governance
  - [x] Regular proposal process
  - [ ] PGF council elections _not tested_
  - [ ] PGF council operations _not tested_
  - [ ] Test upgrade path from launch to fully operational mainnet _not tested_
- MASP
  - [x] MASP implementation
  - [ ] Shielded rewards implementation - the cryptography part is done, the PID part is not
  - [x] Test shielded transfers with NAM
  - [ ] Test shielded transfers with IBC assets
  - [ ] Test shielded transfers with NFTs
  - [ ] Test shielded transfers with ETH & DAI
  - [ ] Test shielded set rewards
- IBC
  - [ ] Test with Osmosis
  - [ ] Test with Cosmos Hub _maybe_
  - [ ] Figure out relayer software compatibility
- Ethereum bridge
  _A lot of this is done, but it's not merged, difficult to evaluate exactly what so far._
  - [x] ETH (wETH), ERC20, ERC721 support
  - [ ] Flow controls
  - [x] Ethereum contracts (Vault, Proxy, Governance, bridge contract)
  - [ ] Test with Ethereum mainnet
  - [ ] Test governance recovery
- Trusted setup
  - [ ] Launch testnet with real TS parameters _tested locally, but not on a testnet?_
- Benchmarking: shielded transfers, wallet UX
